/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.patterns;

import com.patterns.strategy.Fruit;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello");

        FruitIdentificationService fruitIdentificationService = new FruitIdentificationService();

        Fruit kiwi = fruitIdentificationService.identify("green", "cylindric", "small");
        System.out.println("Found : " + kiwi);
        Fruit banana = fruitIdentificationService.identify("yellow", "long", "medium");
        System.out.println("Found : " + banana);
    }
}
